config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :police_districts, except: %i[destroy] do
      resources :meetings, except: %i[show]
      resources :elected_officials, except: %i[show destroy]
    end
    root to: 'police_districts#index'
  end

  resources :police_districts, only: [:index]
  get '/d/:slug', to: 'police_districts#show', as: :police_district

  get '/about', to: 'static_pages#about', as: :about
  root to: 'police_districts#index'
  get '/404', to: 'static_pages#page_not_found'
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  include LinkPrefixHelper

  MEETING_WAIT_PERIOD = 8.hours

  belongs_to :police_district

  scope :upcoming_and_ongoing, -> {
    where('event_datetime > ?', Time.current.utc - MEETING_WAIT_PERIOD).order(event_datetime: :asc)
  }
  scope :past, -> {
    where('event_datetime <= ?', Time.current.utc - MEETING_WAIT_PERIOD).order(event_datetime: :desc)
  }

  def formatted_event_datetime
    if event_datetime == nil
      nil
    else
      day_diff = (event_datetime&.in_time_zone(police_district.timezone).midnight - DateTime.now.in_time_zone(police_district.timezone).midnight).to_i / 86400
      time_format = '%l:%M%P %Z'

      if day_diff == 0
        event_datetime&.in_time_zone(police_district.timezone)&.strftime('Today, ' + time_format)
      elsif day_diff >= 0 && day_diff <= 6
        event_datetime&.in_time_zone(police_district.timezone)&.strftime('%A, ' + time_format)
      else
        event_datetime&.in_time_zone(police_district.timezone)&.strftime('%b %-d, ' + time_format)
      end
    end
  end

  def agenda_link_prefixed
    prefix(agenda_link)
  end

  def video_link_prefixed
    prefix(video_link)
  end
end

app/controllers/admin/meetings_controller.rb
class Admin::MeetingsController < Admin::ApplicationController
  before_action :set_police_district

  include Timezonable

  def new
    @meeting = district.meetings.build

    render :new
  end

  def edit
    @meeting = district.meetings.find(params[:id])
    @meeting.event_datetime = convert_and_strip_timezone(@meeting.event_datetime, @district.timezone)

    render :edit
  end

  def create
    @meeting = @district.meetings.build(meeting_params)
    @meeting.event_datetime = set_timezone(@meeting.event_datetime, @district.timezone)

    if @meeting.save
      redirect_to admin_police_district_path(@district)
    else
      @meeting.event_datetime = convert_and_strip_timezone(@meeting.event_datetime, @district.timezone)
      render :new
    end
  end

  def update
    @meeting = district.meetings.find(params[:id])
    @meeting.assign_attributes(meeting_params)
    @meeting.event_datetime = set_timezone(@meeting.event_datetime, @district.timezone)

    if @meeting.save
      redirect_to admin_police_district_path(@district)
    else
      @meeting.event_datetime = convert_and_strip_timezone(@meeting.event_datetime, @district.timezone)
      render :edit
    end
  end

  def destroy
    @meeting = district.meetings.find(params[:id])
    @meeting.destroy

    respond_to do |format|
      format.js
    end
  end

  private

  attr_reader :district

  def set_police_district
    @district = PoliceDistrict.find_by_slug!(params[:police_district_id])
  end

  def meeting_params
    params.require(:meeting).permit(
      :video_link,
      :event_datetime,
      :agenda_link,
      :agenda_details,
      :how_to_comment,
      :about
    )
  end
end

app/views/admin/meetings/_meeting_form.html.erb
<div class="container">
  <%= simple_form_for [@district, @meeting], url: @meeting.persisted? ? admin_police_district_meeting_path(@district, @meeting) : admin_police_district_meetings_path do |f| %>
    <%= f.input :event_datetime, ampm: true, default: 3.days.from_now.beginning_of_hour.in_time_zone(@district.timezone), label: 'Meeting date and time', wrapper_html: { class: 'form-group--medium' } %>
    <%= f.input :video_link, label: 'Video conference link', wrapper_html: { class: 'form-group--medium' } %>
    <%= f.input :agenda_link, label: 'Meeting agenda link', wrapper_html: { class: 'form-group--medium' } %>
    <%= f.input :agenda_details, label: 'Agenda Details' %>
    <%= f.input :how_to_comment %>
    <%= f.input :about, label: 'About this meeting' %>
    <%= f.submit %>
  <% end %>
</div>

app/views/admin/meetings/destroy.js.erb
location.reload();

app/views/admin/meetings/edit.html.erb
<div class="container">
  <h1>Editing a meeting for: <%= @district.name %></h1>
  <%= render partial: 'meeting_form' %>
</div>

app/views/admin/meetings/index.html.erb
<%= render partial: 'shared/district_header', locals: { district: @district } %>

<div class="container">
  <div>All meetings are in <%= @district.timezone %>.</div>
  <div class="mb-5 mt-5">
    <%= link_to 'Add budget meeting', new_admin_police_district_meeting_path, class: 'btn btn-primary' %>
    <%= link_to 'Edit', edit_admin_police_district_path(@district), class: 'btn btn-primary' %>
  </div>
  <div>
    <% @meetings.each do |meeting| %>
      <div class="district-card">
        <div class="col-md-6">
          <h2 class="h5"><%= meeting.formatted_event_datetime %></h2>
        </div>
        <div class="col-md-4">
          <div class="h5">Phone: <%= meeting.phone_number %></div>
        </div>
        <div class="col-md-2">
          <div class="h5"><a href="<%= edit_admin_police_district_meeting_path(@district, meeting) %>">Edit</a></div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/meetings/new.html.erb
<div class="container">
  <h1>Add a new meeting for: <%= @district.name %></h1>
  <%= render partial: 'meeting_form' %>
</div>