config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :police_districts, except: %i[destroy] do
      resources :meetings, except: %i[show]
      resources :elected_officials, except: %i[show destroy]
    end
    root to: 'police_districts#index'
  end

  resources :police_districts, only: [:index]
  get '/d/:slug', to: 'police_districts#show', as: :police_district

  get '/about', to: 'static_pages#about', as: :about
  root to: 'police_districts#index'
  get '/404', to: 'static_pages#page_not_found'
end

app/models/elected_official.rb
class ElectedOfficial < ApplicationRecord
  belongs_to :police_district
  validates_presence_of :name, :position, :list_rank
end
  

app/controllers/admin/elected_officials_controller.rb
class Admin::ElectedOfficialsController < Admin::ApplicationController
    before_action :set_police_district
  
    def new
      @elected_official = ElectedOfficial.new(police_district: @district)

      render :new
    end
  
    def edit
      @elected_official = ElectedOfficial.find(params[:id])
  
      render :edit
    end
  
    def create
      @elected_official = @district.elected_officials.build(elected_official_params)
  
      if @elected_official.save
        redirect_to admin_police_district_path(@district)
      else
        render :new
      end
    end
  
    def update
      @elected_official = ElectedOfficial.find(params[:id])
      @elected_official.assign_attributes(elected_official_params)
      
      if @elected_official.save
        redirect_to admin_police_district_path(@district)
      else
        render :edit
      end
    end
  
    private
  
    def set_police_district
      @district = PoliceDistrict.find_by_slug(params[:police_district_id])
    end
  
    def elected_official_params
      params.require(:elected_official).permit(:name, :position, :reelection_date, :list_rank)
    end
  end
  

app/views/admin/elected_officials/_elected_officials_form.html.erb
<div class="container">
  <%= simple_form_for [@district, @elected_official], url: @elected_official.persisted? ? admin_police_district_elected_official_path(@district, @elected_official) : admin_police_district_elected_officials_path do |f| %>
    <%= f.input :name, wrapper_html: { class: 'form-group--medium' } %>
    <%= f.input :position, wrapper_html: { class: 'form-group--medium' } %>
    <%= f.input :reelection_date, label: 'Re-election date', wrapper_html: { class: 'form-group--medium' } %>
    <%= f.input :list_rank, wrapper_html: { class: 'form-group--medium' } %>
    <%= f.submit %>
  <% end %>
</div>

app/views/admin/elected_officials/edit.html.erb
<div class="container">
  <h1>Edit elected official for: <%= @district.name %></h1>
  <%= render partial: 'elected_officials_form' %>
</div>

app/views/admin/elected_officials/new.html.erb
<%= render partial: 'shared/district_header', locals: { district: @district } %>

<div class="container">
  <%= form_for [@district, @elected_official], url: @elected_official.persisted? ? admin_police_district_elected_official_path(@district, @elected_official) : admin_police_district_elected_officials_path do |f| %>
    <div><%= @elected_official.errors.full_messages.join("\n") if @elected_official.errors.any? %></div>
    
    <div class="form-group form-group--medium">
      <%= f.label :name, 'Name' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group form-group--medium">
      <%= f.label :position, 'Position' %>
      <%= f.text_field :position, class: 'form-control' %>
    </div>
    <div class="form-group form-group--medium">
      <%= f.label :reelection_date, 'Re-election date' %>
      <%= f.text_field :reelection_date, class: 'form-control' %>
    </div>
    <div class="form-group form-group--medium">
      <%= f.label :list_rank, 'List rank' %>
      <%= f.number_field :list_rank, in: 1..20, step: 1, class: 'form-control' %>
    </div>
    <%= f.submit %>
  <% end %>
</div>