config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :police_districts, except: %i[destroy] do
      resources :meetings, except: %i[show]
      resources :elected_officials, except: %i[show destroy]
    end
    root to: 'police_districts#index'
  end

  resources :police_districts, only: [:index]
  get '/d/:slug', to: 'police_districts#show', as: :police_district

  get '/about', to: 'static_pages#about', as: :about
  root to: 'police_districts#index'
  get '/404', to: 'static_pages#page_not_found'
end

app/models/police_district.rb
class PoliceDistrict < ApplicationRecord
  include Timezonable
  include LinkPrefixHelper

  TIME_ZONE_DEFAULT = Timezonable.default_zone.freeze
  TIME_ZONE_OPTIONS = Timezonable.us_zone_names.freeze

  validates_presence_of :name, :total_police_department_budget
  validates :slug, uniqueness: true, format: { with: /\A[a-z0-9\-]+\Z/ }, allow_blank: true
  validates :timezone, presence: true, inclusion: { in: TIME_ZONE_OPTIONS }

  has_many :meetings, -> { order(:event_datetime) }
  has_many :elected_officials, -> { order(:list_rank) }

  geocoded_by :address
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
  after_validation :set_slug
  reverse_geocoded_by :latitude, :longitude do |obj,results|
    if geo = results.first
      obj.address = "#{geo.city}, #{geo.state}"
    end
  end
  after_validation :reverse_geocode

  include ActionView::Helpers::NumberHelper

  scope :with_upcoming_meetings, -> {
    joins(:meetings).merge(Meeting.upcoming_and_ongoing).uniq
  }

  def self.with_only_past_meetings
    PoliceDistrict.joins(:meetings).merge(Meeting.past).uniq.reject{|p| p.next_meeting.present? }
  end

  def readable_budget
    number_to_human(total_police_department_budget,format:'%n%u',precision: 4, units:{thousand:'K',million:'M',billion:'B'})
  end

  def budget_title
    budget_prefix = "2019 – 2020 "
    used_budget_label = "law enforcement"
    budget_suffix = " budget"

    if budget_label.present?
      used_budget_label = budget_label
    end

    budget_prefix + used_budget_label + budget_suffix
  end

  def next_meeting
    @next_meeting ||= meetings.upcoming_and_ongoing.limit(1).first
  end

  def most_recent_meeting
    @most_recent_meeting ||= meetings.past.limit(1).first
  end

  def elected_officials_contact_link_prefixed
    prefix(elected_officials_contact_link)
  end

  def general_fund_spent_on_police_percentage
    return unless total_general_fund_budget && total_police_paid_from_general_fund_budget

    ((total_police_paid_from_general_fund_budget.to_f / total_general_fund_budget.to_f) * 100).round
  end

  def more_funding_than
    [
      [law_enforcement_gets_more_than_1, law_enforcement_gets_more_than_1_dollars],
      [law_enforcement_gets_more_than_2, law_enforcement_gets_more_than_2_dollars],
      [law_enforcement_gets_more_than_3, law_enforcement_gets_more_than_3_dollars],
    ]
    .filter do |pair|
      pair.all?(&:present?)
    end
    .map do |f|
      {name: f[0], amount: f[1]}
    end
  end

  def to_param
    slug
  end

  private

  def set_slug
    self.slug = slug.present? ? slug : name.to_s.parameterize
  end

end

app/controllers/admin/police_districts_controller.rb
class Admin::PoliceDistrictsController < Admin::ApplicationController
  include GoogleCalendarable

  before_action :set_district, except: [:new, :create, :index]

  def new
    @district = PoliceDistrict.new(timezone: PoliceDistrict::TIME_ZONE_DEFAULT)

    render :new
  end

  def create
    @district = PoliceDistrict.new(district_params)

    if @district.valid?
      @district.save
      redirect_to admin_police_districts_path
    else
      render :new
    end
  end

  def show
    render :show
  end

  def edit
    render :edit
  end

  def update
    if @district.update(district_params)
      redirect_to admin_police_districts_path
    else
      render :edit
    end
  end

  def index
    @districts = PoliceDistrict.all
  end

  private

  def set_district
    @district = PoliceDistrict.find_by_slug!(params[:id])
  end

  def district_params
    params.require(:police_district).permit(
      :name,
      :slug,
      :total_district_budget,
      :total_police_department_budget,
      :total_general_fund_budget,
      :total_police_paid_from_general_fund_budget,
      :timezone,
      :address,
      :decision_makers_text,
      :elected_officials_contact_link,
      :law_enforcement_gets_more_than_1,
      :law_enforcement_gets_more_than_2,
      :law_enforcement_gets_more_than_3,
      :law_enforcement_gets_more_than_1_dollars,
      :law_enforcement_gets_more_than_2_dollars,
      :law_enforcement_gets_more_than_3_dollars,
      :budget_label,
     )
  end
end

app/controllers/police_districts_controller.rb
class PoliceDistrictsController < ApplicationController
  include GoogleCalendarable

  def index
    @districts_with_future_meetings = (params[:near].present? ? PoliceDistrict.near(params[:near]) : PoliceDistrict.all).with_upcoming_meetings
    @districts_with_past_meetings = (params[:near].present? ? PoliceDistrict.near(params[:near]) : PoliceDistrict.all).with_only_past_meetings
  end

  def show
    @district = PoliceDistrict.find_by_slug!(params[:slug])
    @meeting = @district.next_meeting.present? ? @district.next_meeting : @district.most_recent_meeting
  end
end

app/views/admin/police_districts/_district_form.html.erb
<div class="container">
  <%= simple_form_for @district, url: @district.persisted? ? admin_police_district_path(@district) : admin_police_districts_url do |f| %>
      <%= f.input :name, wrapper_html: { class: 'form-group--medium' } %>

      <% if @district.slug.present? %>
        <%= f.input :slug, wrapper_html: { class: 'form-group--medium' } %>
      <% end %>

      <%= f.input :address, wrapper_html: { class: 'form-group--medium' } %>
      <%= f.input :timezone, collection: PoliceDistrict::TIME_ZONE_OPTIONS, wrapper_html: { class: 'form-group--medium' } %>
      <%= f.input :total_police_department_budget, label: 'Total Law Enforcement FY 19-20 Budget', wrapper_html: { class: 'form-group--medium' } %>
      <%= f.input :budget_label, label: 'Optional alternate label for law enforcement', wrapper_html: { class: 'form-group--medium' } %>
      <%= f.input :total_district_budget, label: 'Total FY 19-20 City Budget', wrapper_html: { class: 'form-group--medium' } %>
      <%= f.input :total_general_fund_budget, label: 'Total FY 19-20 General Fund Budget', wrapper_html: { class: 'form-group--medium' } %>
      <%= f.input :total_police_paid_from_general_fund_budget, label: 'Total FY 19-20 General Fund Spent on Police', wrapper_html: { class: 'form-group--medium' } %>
      <%= f.input :decision_makers_text %>
      <%= f.input :elected_officials_contact_link, label: 'Decision makers contact link' %>

      <div class="form-group">
        <%= f.label :law_enforcement_gets_more_than_1, 'Law enforcement gets more than #1' %>
        <%= f.text_field :law_enforcement_gets_more_than_1, class: 'form-control' %>
        <%= f.number_field :law_enforcement_gets_more_than_1_dollars, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :law_enforcement_gets_more_than_2, 'Law enforcement gets more than #2' %>
        <%= f.text_field :law_enforcement_gets_more_than_2, class: 'form-control' %>
        <%= f.number_field :law_enforcement_gets_more_than_2_dollars, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :law_enforcement_gets_more_than_3, 'Law enforcement gets more than #3' %>
        <%= f.text_field :law_enforcement_gets_more_than_3, class: 'form-control' %>
        <%= f.number_field :law_enforcement_gets_more_than_3_dollars, class: 'form-control' %>
      </div>

      <%= f.submit  %>
  <% end %>
</div>

app/views/admin/police_districts/edit.html.erb
<div class="container">
  <h1>Editing district: <%= @district.name %></h1>
  <%= render partial: 'district_form' %>
</div>

app/views/admin/police_districts/index.html.erb
<div class="container">
  <div class="mb-5">
    <%= link_to 'Add a new district', new_admin_police_district_path, class: 'btn btn-primary' %>
  </div>

  <% @districts.each do |district| %>
      <%= render partial: 'shared/district_card', locals: { district: district, district_path: admin_police_district_path(district) } %>
  <% end %>
</div>

app/views/admin/police_districts/new.html.erb
<div class="container">
  <h1 class="h3">Add a new police district</h1>
  <%= render partial: 'district_form' %>
</div>

app/views/admin/police_districts/show.html.erb
<%= render partial: 'shared/district_header', locals: { district: @district } %>

<div class="container">
  <div class="mb-5">All meetings are in <%= @district.timezone %>.</div>
  <div class="mb-5">
    <%= link_to 'Add meeting', new_admin_police_district_meeting_path(@district), class: 'btn btn-primary' %>
    <%= link_to 'Add elected officials', new_admin_police_district_elected_official_path(@district), class: 'btn btn-primary' %>
    <%= link_to 'Edit', edit_admin_police_district_path(@district), class: 'btn btn-primary' %>
  </div>
  <div class="mb-5">
    <h2>Meetings</h2>
    <table class="table table-striped" data-spec="meetings">
      <thead>
        <tr>
          <th scope="col">Date</th>
          <th scope="col"> </th>
          <th scope="col"> </th>
        </tr>
      </thead>
      <tbody>
        <% @district.meetings.each do |meeting| %>
          <tr id=<%= "meeting-#{meeting.id}" %>>
            <td><%= meeting.formatted_event_datetime %></td>
            <td><%= link_to "Edit", edit_admin_police_district_meeting_path(@district, meeting), class: 'button'  %></td>
            <td><%= link_to "Delete",
                            admin_police_district_meeting_path(@district, meeting),
                            method: :delete,
                            class: 'button',
                            data: { remote: true }  %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="mb-5">
    <h2>Elected Officials</h2>
    <table class="table table-striped" data-spec="officials">
      <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Position</th>
        <th scope="col">Re-election date</th>
        <th scope="col"> </th>
      </tr>
      </thead>
      <tbody>
      <% @district.elected_officials.each do |elected_official| %>
          <tr id=<%= "official-#{elected_official.id}" %>>
            <td><%= elected_official.name %></td>
            <td><%= elected_official.position %></td>
            <td><%= elected_official.reelection_date %></td>
            <td><%= link_to "Edit", edit_admin_police_district_elected_official_path(@district, elected_official), class: 'button' %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>