config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :police_districts, except: %i[destroy] do
      resources :meetings, except: %i[show]
      resources :elected_officials, except: %i[show destroy]
    end
    root to: 'police_districts#index'
  end

  resources :police_districts, only: [:index]
  get '/d/:slug', to: 'police_districts#show', as: :police_district

  get '/about', to: 'static_pages#about', as: :about
  root to: 'police_districts#index'
  get '/404', to: 'static_pages#page_not_found'
end

app/views/layouts/_google_analytics.html.erb
<% if ENV['GOOGLE_ANALYTICS'].present? %>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=<%= ENV['GOOGLE_ANALYTICS'] %>"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', "<%= ENV['GOOGLE_ANALYTICS'] %>");
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reinvest in us.</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= render 'layouts/google_analytics' %>
    <%= javascript_pack_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Find where and how to give public comment on police budgets.">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="<%= request.url %>">
    <meta property="og:title" content="<%= open_graph_title %>">
    <meta property="og:description" content="<%= open_graph_description %>">
    <meta property="og:image" content="https://res.cloudinary.com/carvin/image/upload/v1592780255/riu.png">

    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="<%= request.url %>">
    <meta property="twitter:title" content="<%= open_graph_title %>">
    <meta property="twitter:description" content="<%= open_graph_description %>">
    <meta property="twitter:image" content="https://res.cloudinary.com/carvin/image/upload/v1592780255/riu.png">
  </head>

  <body class="<%= body_classes.join(' ') %>">
      <nav class="navbar navbar-expand-lg justify-content-between">
        <%= link_to '', root_path, class: 'navbar-brand' %>
        <div class="navbar-nav">
          <% if user_signed_in? %>
            <%= link_to('Add info', admin_root_path, class: 'nav-link') %>
            <%= link_to('Log out', destroy_user_session_path, method: :delete, class: 'nav-link') %>
          <% end %>
          <%= link_to('About', about_path, class: 'nav-link') %>
        </div>
      </nav>
    <% if notice %>
      <div class="alert alert-primary" role="alert">
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end %>

    <main role="main">
      <%= yield %>
    </main>
  </body>
</html>